name: Benchmark

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: bench-${{ hashFiles('yarn.lock') }}

      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: 'Build ts'
        run: yarn build

      - name: 'Run benchmark'
        run: node -r @swc-node/register ./bench/index.ts | tee bench.txt

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        if: github.ref == 'refs/heads/main'
        with:
          tool: 'benchmarkjs'
          output-file-path: bench.txt
          github-token: ${{ secrets.GH_TOKEN }}
          auto-push: true

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        if: github.ref != 'refs/heads/main'
        continue-on-error: true
        with:
          tool: 'benchmarkjs'
          output-file-path: bench.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: true
          auto-push: false
